sudo: required
services:
  - docker

before_install:
  - docker build -t sirskip/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true sirskip/docker-react npm run test -- --coverage

language: generic

after_success:
  - docker build -t sirskip/milti-client ./client
  - docker build -t sirskip/milti-nginx ./nginx
  - docker build -t sirskip/milti-server ./server
  - docker build -t sirskip/milti-worker ./worker
  # Log into the Docker Hub CLI
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u " $DOCKER_HUB_ID" --password-stdin
  # take the images and push them to Docker Hub
  - docker push sirskip/milti-client
  - docker push sirskip/milti-nginx
  - docker push sirskip/milti-server
  - docker push sirskip/milti-worker


