version: '3'

services: 

  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  nginx:
    # make sure the container is always running
    restart: always
    build:
      # use the Dockerfile.dev in the ./nginx folder to do the build
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'

  api:
    build:
      # use the Dockerfile.dev in the ./server folder to do the build
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      # don't override use of the /app as the doc root for the /node_modules folder.  still use from /app/node_modules
      - /app/node_modules
      # do override the rest of the apps and have them pull from local ./server instead of app -- exept for the above
      # meaning that any call to the /app in the container will actuall pull from the ./server on workstation instead of in docker container
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  client: 
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379




